Added GIFAnimSprite get/set loop mode, changed callback to use std::function
CircuitMess/CircuitOS pull request #126
Opened 2022-06-09 14:21 UTC by MiLeG

Used in new CircuitPet

2022-06-13 22:02 UTC, filipbudisa requested changes

2022-06-13 22:02 UTC, filipbudisa commented on src/Display/GIFAnimatedSprite.cpp
> +				return true;
pozove se next frame, nema idućeg, resetira se gif, ali se novi prvi frame ne prekopira u currentFrame.data. prema ovom kodu se nextFrame treba dva puta pozvat nakon zadnjeg framea da bi se dobio opet prvi frame.
isto vrijedi i za LoopMode::AUTO granu

2022-06-13 22:02 UTC, filipbudisa commented on src/Display/GIFAnimatedSprite.cpp
> +				if(gif->loop_count != 0 && loopCount == gif->loop_count) return false;
koliko vidim, nigdje ne povečavaš loopCount

2022-06-13 22:02 UTC, filipbudisa commented on src/Display/GIFAnimatedSprite.h
> +enum class LoopMode { AUTO, SINGLE, INFINITE };
PascalCase molim te

2022-06-15 11:53 UTC, MiLeG commented on src/Display/GIFAnimatedSprite.cpp
> +				return true;
Napravljen task da se odvoji logika i crtanje ove klase

2022-06-24 12:22 UTC, merged